### ISSUE TITLE
Initial Building Pain Points

### ISSUE THREAD

**Issue by fleischie** [KenzieMac130/CitrusToolbox#7] opened 2021-06-04 10:01 UTC
Hello,

as arranged on twitter I took the liberty to test out a fresh build of the project.

Some initial points I encountered:
- At first `.\tools\CMakeLists.txt` contains an `add_subdirectory(gltf2citrus)` statement, only that the directory doesn't exist. Removing this line from the file fixes this.
- The next problem was, that the `tracy` git submodule needed to be cloned manually (resp. `git submodule init; git submodule update`). This could probably have been documented in the guide, by stating "Clone the project [...] using `git clone --recurse-submodules <target>`".
- Then I got a compiler error, here: https://github.com/KenzieMac130/CitrusToolbox/blob/09a21516dfae0ac63966f4c97d45516e397364bf/engine/renderer/vulkan/VkBackend.cpp#L379-L381 The message was basically that the signature of `vAllocFunction` (and the next two assignments) cannot be converted to `PFN_vkAllocationFunction`. I was able to fix this by explicitly casting the function to that typedef, i.e. `vkAllocCallback.pfnAllocation = (PFN_vkAllocationFunction) vkAllocFunction`. (I can give you details of my setup, if you can guide me through what you would need.
- Afterwards the compilation requested SDL, which was available but only for `x64` but required for `x86` which was completely missing.

As these are several smaller/trivially fixable issues, I refrained from posting this in the general feedback issue. Additionally, if you need me to re-formulate a point and/or provide details, let me know.

:)

**Comment by KenzieMac130** [comment] 2021-06-04 10:48
`* At first .\tools\CMakeLists.txt contains an add_subdirectory(gltf2citrus) statement, only that the directory doesn't exist. Removing this line from the file fixes this.`
(fixed, didn't push that)

`* The next problem was, that the tracy git submodule needed to be cloned manually (resp. git submodule init; git submodule update). This could probably have been documented in the guide, by stating "Clone the project [...] using git clone --recurse-submodules <target>".`
Will add that to the install instructions. I wasn't aware of that submodule isssue.

`* Then I got a compiler error, here: ...`
Huh, weird... Are you using something other than MSVC? Not even a warning there. Either way I will cast that.

`* Afterwards the compilation requested SDL, which was available but only for x64 but required for x86 which was completely missing.`
32-bit x86 is not supported by the engine because it's pretty much legacy at this point. That is why 64 bit libraries are only provided. I will try to specifically note to build x64.

**Comment by fleischie** [comment] 2021-06-04 11:14
I used `msbuild.exe` directly (specifically `MSBuild.exe .\CitrusToolbox.sln /v:m`). On the other hand setting the arch platform to 64 bit makes the compiler error disappear...

**Comment by KenzieMac130** [comment] 2021-06-04 11:44
> I used `msbuild.exe` directly (specifically `MSBuild.exe .\CitrusToolbox.sln /v:m`). On the other hand setting the arch platform to 64 bit makes the compiler error disappear...

Alright, I pushed the cast changes anyways. Now does going from a fresh clone following the guide run smoothly? 

(Keep the Win64 libs when you retry, that eats up the LFS quota because I cant find any free/reliable command line alternative for file hosting)

**Comment by fleischie** [comment] 2021-06-04 12:24
I reverted my local changes, merged the latest main branch to have this fully "fresh clone" feeling without re-cloning. I additionally re-ran cmake using a 64bit-only command prompt on windows (not too big on the VS/IDE things) + msbuild call. 

Compilation successful!

The test app crashes though, because it cannot look up "vkCreateInstance() Failed to create vulkan instance." This error was on the command line: `Assertion failed: index < Count(), file c:\users\kfleischmann\code\citrustoolbox\engine\utilities\StaticArray.hpp, line 132`, this was the cause: https://github.com/KenzieMac130/CitrusToolbox/blob/a92415a596a9baa22dce3dd6db380e32634a04a1/engine/renderer/vulkan/VkBackend.cpp#L432-L433

**Comment by KenzieMac130** [comment] 2021-06-04 12:45
Okay, the assertion seems to be related a correction I did in bounds checking the static array and it's UB messed up the string translation system, it wanted to display that text (or a localized version) in a message box. I fixed that if you want to pull.

The failure to create a Vulkan instance however, is not related. Failure to create an instance means the engine hasn't even gotten to the base where it queries for your GPU which makes me think it's a driver issue. The engine expects Vulkan 1.2 which is pretty new. Try updating your graphics drivers and if the issue persists can you run vulkaninfo if you have the LunarG Vulkan SDK installed and give the resulting system specs?

I want to make sure I convey the correct information to the user in that message to help them get past the issue as that is end-user-facing so any information will help.

(Edit, noticed a dumb mistake in a macro usage, pushed a fix. Might be relevant.)

**Comment by fleischie** [comment] 2021-06-04 12:59
Newest version compiles, and displays the error correctly. (At least it now displays a message box with the warning.)

But I have (now) the latest drivers (nvidia GeForce GTX 760 with driver version 466.63), and `vulkaninfo` also says (among other things): `Vulkan Instance Version: 1.2.162`.

**Comment by KenzieMac130** [comment] 2021-06-04 13:02
In the last few minutes I updated something after looking over some code, the macro usage to select a version was incorrect and I didn't notice, was UB. (VK_VERSION_1_2 was changed to VK_API_VERSION_1_2)

**Comment by fleischie** [comment] 2021-06-04 13:31
I already had the macro-related fix when testing the AppTest build (it seems because git said everything up to date). I tried some other tools that validated vulkan, also the sdk tools, etc. And they all seem to work.

Is there something else I should check? Maybe trace the startup and see whether there is some missing/incorrect configuration going on?

**Comment by KenzieMac130** [comment] 2021-06-04 15:51
> I already had the macro-related fix when testing the AppTest build (it seems because git said everything up to date). I tried some other tools that validated vulkan, also the sdk tools, etc. And they all seem to work.
> 
> Is there something else I should check? Maybe trace the startup and see whether there is some missing/incorrect configuration going on?

Go for it. There shouldn't be much ground to cover since it is failing at the instance creation. All it is doing there is filling out metadata about the app/engine and requesting some instance extensions/validation layers. If you have any questions I'll help as much as I can, definitely want to get device/driver compat issues fixed.

RenderDoc also doesn't seem to like latching in until I fixed the macro, so I genuinely might have just made an odd, subtle mistake. I'll try to take a closer look at it tomorrow, (I've been up all night) but I might not be able to hunt down the exact issue due to reproduction issues. 

Only thing on my end I can really think of is the memory allocator callback being weird. Vulkan had some strange requirements which required some pretty weird pointer math, which might be incorrect. In which case you can revert to default by passing NULL to vkAllocCallback on Create/Destroy.

**Comment by fleischie** [comment] 2021-06-10 09:24
Hello.

I tried again today:
- `git fetch --all`
- `git merge origin/main` <- "Already up to date"
- `cd .\build`
- `MSBuild.exe .\CitrusToolkit.sln`
- `.\output\Debug\AppTest.exe`

...

And it gave me the demo without the previously mentioned startup error. So I guess the error was due to my video driver, or my otherwise misconfigured setup last time I tried.

![Annotation 2021-06-10 111755](https://user-images.githubusercontent.com/2211050/121499391-9fbf4580-c9dd-11eb-88d2-4f5052b5f6b7.png)

The only "error" I get now is:
```
[ERROR] VK Validation Layer: [Validation] Code 0 : Validation Error: [ VUID-vkCmdPipelineBarrier-dependencyFlags-01186 ] Object 0: handle = 0x17ca8557e20, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x97273504 | vkCmdPipelineBarrier(): .dependencyFlags VK_DEPENDENCY_VIEW_LOCAL_BIT must not be set outside of a render pass instance The Vulkan spec states: If fname:vkCmdPipelineBarrier is called outside of a render pass instance, VK_DEPENDENCY_VIEW_LOCAL_BIT must not be included in the dependency flags (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdPipelineBarrier-dependencyFlags-01186)
```

Once per frame. The handle is repeated 3 times and has 3 different values, then it repeats. E.g.:
```
[...] handle = 0x1a452b69600 [...]
[...] handle = 0x1a452b69600 [...]
[...] handle = 0x1a452b69600 [...]
[...] handle = 0x1a452b0ffa0 [...]
[...] handle = 0x1a452b0ffa0 [...]
[...] handle = 0x1a452b0ffa0 [...]
[...] handle = 0x1a44cea4be0 [...]
[...] handle = 0x1a44cea4be0 [...]
[...] handle = 0x1a44cea4be0 [...]
[...] handle = 0x1a452b69600 [...]
```

**Comment by KenzieMac130** [comment] 2021-06-10 09:31
Thank you! 

That validation issue surrounding synchronization is new to me, seems to be coming from the composite->presentation blit. Must be because your validation layers are more up to date. I am having some screen blanking issues at high frame rates, that might be the cause. Error makes sense as view local memory synchronization assumes tiled based rendering, outside passes cannot assure that. Will take note of it and fix it.

**Closed as completed by KenzieMac130** 2021-06-10 09:31 UTC
